### ISSUE TITLE
Version Assemblies fails on Mac agent

### ISSUE THREAD

**Issue by nzthiago** [colindembovsky/cols-agent-tasks#10]
The Version Assemblies task fails when run on a Mac because of the backslash used between sourcePath and filePattern (should be forward slash on the Mac)
Should be easy to fix like the VSTS team did here (line 77 and 78):
https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/XamarinLicense/xamarinlicense.ts

**Comment by nzthiago** [comment]
(was going to fix it myself but no time to test it! GahHH!)

**Comment by jamesmontemagno** [comment]
Also a blocker for me :( Anyway to clean this up?

**Comment by colindembovsky** [comment]
I've added the fix (thanks for pointing it out @nzthiago) but don't have a Mac to really test, so I'll leave this open for now.

**Comment by nzthiago** [comment]
Thanks Colin! The same applies to the Replace Tokens one too :smiley:

**Comment by colindembovsky** [comment]
Thanks @nzthiago I fixed the issue in both tasks 😃
