### ISSUE TITLE
ConnectionString replacement not applied?

### ISSUE THREAD

**Issue by advapiIT** [colindembovsky/cols-agent-tasks#101]
Hello Colin,
Please excuse me again but I've found not a way to ask you privately... following your guide [here ](https://colinsalmcorner.com/post/end-to-end-walkthrough-deploying-web-applications-using-team-build-and-release-management) you put for connectionString __AppDbContextStr__ and you say that 

> The publish profile takes care of the connection strings – but you will have noticed that it doesn’t ask for values for appSettings (or any other configuration) anywhere.

So as far I've understood there's no need to put in the Parameters.xml the __AppDbContextStr__ but just inside the Release configuration in TFS...whell I've tried it but it doesn't seem to take care... 
is there something stupid I'm missing?

Thanks in advance

**Comment by colindembovsky** [comment]
@advapiIT this isn't a question related to this repo, you can respond on the blog if you have additional questions or get me on twitter @colindembovsky
