### ISSUE TITLE
Regular expression with postive lookahead and lookbehind is considered invalid

### ISSUE THREAD

**Issue by frankvaneykelen** [colindembovsky/cols-agent-tasks#102]
This Token Regex ...

> `(?<=\")__\w+[-]*[\.\w+-]*__(?=\")`

... results in this error ...

>  `##[error]Invalid regular expression: /(?<=\")__\w+[-]*[\.\w+-]*__(?=\")/: Invalid group`

.. while according to the .NET Regex Tester (http://regexstorm.net/tester) it's valid.

What I'm trying to do is only match tokens like this (within quotes):

> `apiUrl:"__CustomerPortal.ClientAPI.Url__"`

and exclude tokens (generated by an Angular build) like this:

> `(o=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}`

EDIT - I also tried this:
`"__(\w+[-]*[\.\w+-]*)__"`
but that resulted in the quotes being removed after the tokenization.

EDIT #2:
` (?<=\")__(\w+[-]*[\.\w+-]*)__(?=\")` 
results in
` ##[error]Invalid regular expression: /(?<=\")__(\w+[-]*[\.\w+-]*)__(?=\")/: Invalid group` 
too.

**Comment by colindembovsky** [comment]
@frankvaneykelen I'd suggest you simply change the `__` to some other symbol like `%%` so that you don't get conflicts with Angular `__`.

**Comment by frankvaneykelen** [comment]
Since the `__` is in all of our hundreds of builds and releases one does not simply change it. We now have to use a hardcoded regex (` __(CustomerPortal\.ClientAPI\.Url|gwa_Account)__`) in our Angular releases, which is bad, but since it only needs to replace two tokes for most of these release it's not a big problem.
