### ISSUE TITLE
VersionAssemblies - changing the format of the build number in the version number

### ISSUE THREAD

**Issue by fredcicles** [colindembovsky/cols-agent-tasks#103]
I am using the VersionAssemblies task.  I followed your samples and have come close to what I am trying to accomplish but got stuck.  This is a .net project with an AssemblyInfo.cs file.  

My build number in VSTS comes as:  20181003.5

Where the first part is the date and the second part is the # of the build for that date.  As 20181003 is too long to be part of the version string, I want to break that apart and set my version number to:  2018.10.03.5.

Is there a way to accomplish this?

**Comment by colindembovsky** [comment]
Hi @fredcicles - yes, you can use a [logging command](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#updatebuildnumber-override-the-automatically-generated-build-number) to update the build number. If you do this prior to executing VersionAssemblies, then it should all match.
