### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by pipocadr** [colindembovsky/cols-agent-tasks#106]
Hi Colin,

I want to get the full matches from regex and join in one string.

Your task have the 'Build Regex Group Index' to send the position of match.

It's possible to put like '*' to get all matchs found on regex?

Exemple:

Build Number: 1.5.0.99
Custom Regex Find Pattern: \d+
Output: 15099

**Comment by colindembovsky** [comment]
@pipocadr I'm happy to take a PR :-)
