### ISSUE TITLE
Variables which have hyphens (-) in their names are not getting replaced with values

### ISSUE THREAD

**Issue by prabhushrikant** [colindembovsky/cols-agent-tasks#107]
So I had env variable __NEXUS-USERNAME__ and __NEXUS-PASSWORD__ to be replaced in my deploy/mvn/settings.xml file which looked like this 
`<settings>
  <servers>
    <server>
      <id>nexus-cc</id>
      <username>__NEXUS-USERNAME__</username>
      <password>__NEXUS-PASSWORD__</password>
    </server>
  </servers>
</settings>`

and the task never replaced them with my set values. Had to change them to NEXUSUSERNAME and NEXUSPASSWORD

**Comment by colindembovsky** [comment]
@prabhushrikant thanks - I think I'm happy with the way this works - you can customize the REGEX pattern if you really want hyphens.
