### ISSUE TITLE
ReplaceMe/Tokenizer readme suggestion

### ISSUE THREAD

**Issue by MicahGV** [colindembovsky/cols-agent-tasks#108]
Hello,

I had a problem with the default Token Regex parameter as It wasn't finding an item that has an array selector in it. The exact example I ran into was 
`__Serilog.WriteTo[0].Args.connectionString__`
But I fixed it by modifying the Token Regex to `__(\w+[\.\[\]\w+]*)__`

So, can we change the  readme suggested token?
` __(\w+[\.\w+]*)__`
 to 
`__(\w+[\.\[\]\w+]*)__`

as that would cover arrays, and it appears that pattern doesn't break the whole thing

**Comment by colindembovsky** [comment]
@MicahGV please submit a PR :-)
