### ISSUE TITLE
Web deploy task does not handle cmd path with spaces

### ISSUE THREAD

**Issue by CtrlDot** [colindembovsky/cols-agent-tasks#11]
Thanks for creating such an awesome package.  I've noticed that if my branch names have spaces in them, the cmd file will fail to run.  Here is an example log from VSTS Online:

> 2016-04-05T16:03:22.0212411Z cmd /c C:\a\0f79b84a2\xxx - Feature (xxxx) build\drop\rest\of\path /Y "/M:https://xxx.scm.azurewebsites.net:443/msdeploy.axd" "/u:$xxx" "/p:*****" /a:Basic
 

> 2016-04-05T16:03:22.0442412Z ##[error]'C:\a\0f79b84a2\xxx' is not recognized as an internal or external command,

I think the only change that needs to be made is on line 91.  The $cmdfile argument should be explicitly quoted.

**Comment by colindembovsky** [comment]
Thanks @CtrlDot - turns out the fix wasn't quite that simple, but I think I've fixed it. Closing this for now unless you still have issues with the Task.

**Comment by CtrlDot** [comment]
Colin,

I haven't been able to test the spacing, but it does seem like the cmdargs is not working now to the webdeploy.

Specifically around Azure user names.

Here is the output from the write-host statement
"/u:$pcl-dev-hmp-api-906"

And here is what web-deploy shows

userName="-dev-hmp-api-906"

This worked yesterday for sure.

**Comment by colindembovsky** [comment]
Ok so I introduced a bug - the $ symbol in the username was being treated as a variable. So the username arg looked like `/u:$bob-site` but ended up being `-site` (since there is no variable called `$bob`.
