### ISSUE TITLE
Installing on TFS Build Server

### ISSUE THREAD

**Issue by sarfraz17** [colindembovsky/cols-agent-tasks#113]
Hi,
      Can you please let me know if I need to install this on the build server and how can I configure.

Thanks & Regards,
Sarfraz.

**Comment by colindembovsky** [comment]
@sarfraz17 No you just install this onto TFS using the Extension page (in the web page). You do not need to install this onto each build server.

[Here's](https://docs.microsoft.com/en-us/azure/devops/marketplace/get-tfs-extensions?view=azure-devops-2019) a link to a doc that will walk you through how to do this.
