### ISSUE TITLE
Fail if coverage delta is below 30

### ISSUE THREAD

**Issue by decadehew** [colindembovsky/cols-agent-tasks#114]
I will get failed 
log:

##[debug]Detected username: creating basic cred handler
##[debug]Connecting to test API
##[debug]Getting coverage data
##[debug]Analyzing coverage data
##[debug]task result: Failed
##[error]Coverage delta is below the threshold of 30
##[debug]Processed: ##vso[task.issue type=error;]Coverage delta is below the threshold of 30
##[debug]Processed: ##vso[task.complete result=Failed;]Coverage delta is below the threshold of 30
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]Code coverage delta is above the threshold of 30
##[debug]Leaving Coverage Gate task
##[section]Finishing: Fail if coverage delta is below 30

**Comment by colindembovsky** [comment]
@decadehew - This is exactly correct - it looks like you've set the task to fail the release if the build coverage is under 30%. The task is getting the coverage and it appears to be less than 30%, so it is failing the release.

Are you expecting a different result?

**Comment by decadehew** [comment]
@colindembovsky Thanks for reply.

Another issues: ##[error]**There are no coverage deltas. Make sure you have at least 2 builds.**

log:
```
##[debug]minDelta: 80
##[debug]operator: lt
##[debug]username: frontend-test
##[debug]System.AccessToken=undefined
##[debug]Detected username: creating basic cred handler
##[debug]Connecting to test API
##[debug]Getting coverage data
##[debug]Analyzing coverage data
##[debug]task result: Failed
##[error]There are no coverage deltas. Make sure you have at least 2 builds.
##[debug]Processed: ##vso[task.issue type=error;]There are no coverage deltas. Make sure you have at least 2 builds.
##[debug]Processed: ##vso[task.complete result=Failed;]There are no coverage deltas. Make sure you have at least 2 builds.
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]Code coverage delta is above the threshold of 80
##[debug]Leaving Coverage Gate task
##[section]Finishing: Fail if coverage delta is below 80
```

Coverage Result
![](https://i.loli.net/2019/03/19/5c90a533ba597.png)

**Comment by colindembovsky** [comment]
@decadehew This task works by comparing the delta (difference) between the code coverage of 2 builds. Just queue another build so that there is a baseline to compare.
