### ISSUE TITLE
Dacpac schema compare is not compatible with new url-schema in Azure DevOps

### ISSUE THREAD

**Issue by NowinskiK** [colindembovsky/cols-agent-tasks#116]
Hi Colin. Thank for your efforts.
I tried to use "Dacpac schema compare", but I couldn't manage to set it up correctly.
I checked this file: **TestScript.ps1** which suggests (https://$vstsAcc.visualstudio.com/) that the module is compatible only with old URL types or with VSTS only. 
My organisation is using new one like: 
https://dev.azure.com/organ/project-name/_build/results?buildId=107&view=results
Is that right?

https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sep-10-azure-devops-launch#administration

**Comment by colindembovsky** [comment]
Hi @NowinskiK 

The old URL will still work - there could be an issue with VS2019 though - see #117 . What error are you seeing?
