### ISSUE TITLE
The comparison is always reversed

### ISSUE THREAD

**Issue by JRobinsIken** [colindembovsky/cols-agent-tasks#128]
The check inside dacpacreport.ps1 for $reverse on line 238 always evaluates to true.

see https://github.com/colindembovsky/cols-agent-tasks/pull/127 for fix

**Comment by colindembovsky** [comment]
@JRobinsIken I spoke too early on your PR - I think the `Get-Parameter` method is making the boolean value a string, which is why the `-eq $true` is necessary. Anyway, it's fixed in aa8e88c5d4c8d0b9ba64a065afade21b657403c1. Thanks for the update!
