### ISSUE TITLE
[DacPacReport] Fails for YAML pipeline with: Could not find token for autheniticating. Please enable OAuth token in Build/Release Options

### ISSUE THREAD

**Issue by NenoLoje** [colindembovsky/cols-agent-tasks#131]
In a YAML-based pipeline, the task fails with the following error message:

> ##[error]Could not find token for autheniticating. Please enable OAuth token in Build/Release Options

However, the pipeline is a YAML-based pipeline and the access token should be available to the task as a secret.

PS: And btw, there's a typo in the error message. :)

Thanks,
--Neno

**Comment by colindembovsky** [comment]
Thanks @NenoLoje - fixed in v 1.4.114 (see e784331548cf9c16a8e6a5e10b3d03f3213fc7ab).
