### ISSUE TITLE
Issue with DACPAC Schema compare

### ISSUE THREAD

**Issue by mramanna** [colindembovsky/cols-agent-tasks#132]
Hi Colin, I have been using dacpac schema compare task and I've got it working in my build but when I look at my summary on the build I get very minimal information on the change. Nothing like what you show @ https://github.com/colindembovsky/cols-agent-tasks/tree/master/Tasks/DacPacReport

Also don't see the change script section either.

**Comment by colindembovsky** [comment]
Hi @mramanna can you please share a screenshot of what you're seeing? Also, in the "new" build summary UI, you have to click on the "Extensions" tab to see the attached markdown:

![image](https://user-images.githubusercontent.com/1932561/66150777-bd15fc80-e5ca-11e9-8770-2fd67f046e97.png)

**Comment by mramanna** [comment]
Hi Colin

Thanks for getting back to me. I don't see the extensions tab in the build summary. Is there a feature I need to add in order to get that tab?

![BuildSummary](https://user-images.githubusercontent.com/55881978/66200500-1cdad900-e699-11e9-962c-6d5f013c9824.jpg)

**Comment by colindembovsky** [comment]
Hi @mramanna looks like you're on the "classic" view. To get the new view, enable the `New build result page` preview feature for your profile. The extension adds 2 sections to the summary: `Schema Change Summary` (which is showing in the report) and below that there should be a `Change Script` section. I'm not sure why you're not seeing the 2nd section. Can you run a new build with variable `system.debug` set to `true` and paste in the logs for the Dacpac Compare task (feel free to clean them on any sensitive info)?
