### ISSUE TITLE
Tag Task Azure DevOps Server 2019 Compatibility?

### ISSUE THREAD

**Issue by Celaires** [colindembovsky/cols-agent-tasks#144]
I added the Tag Build or Release Task to my build pipeline but it fails with the following error:

`Could not find token for autheniticating. Please enable OAuth token in Build/Release Options.`

I did a bit of digging and it seems like I might need to enable "Allow scripts to access the OAuth token" in my build options? Although, that option doesn't appear on my build options tab. In any case do you have any insight as to what could be going on? Is the task compatible with Azure DevOps Server 2019?

Thanks!

**Comment by colindembovsky** [comment]
Hi @Celaires - I'm guessing you're using YAML build and not the Classic (UI), right? The "OAuth token" is something you enable in the UI. To enable it in YAML, you need to add `persistCredentials` to the checkout task, like so:

```yml
steps:
- checkout: self
  persistCredentials: true
```
The `persistCredentials: true` places the OAuth token into a system variable, `SYSTEM_ACCESSTOKEN` which is what the Tag Build or Release Task uses internally.

See [this issue](https://github.com/Microsoft/azure-pipelines-agent/issues/1827).

Let me know if that unblocks you!

**Comment by Celaires** [comment]
Ok, that's kind of what I stumbled across this morning too. However, I am using the Classic (UI) and there doesn't appear to be an option persist credentials or "Allow scripts to access the OAuth token".

**Comment by Celaires** [comment]
Ha, of course, as soon as I commented I found the the "Allow scripts to access the OAuth token" setting (it's kind of hidden in the UI). Things are working now. Thanks for your help!
