### ISSUE TITLE
Tokenize File Task - Leave an empty line at the end of the file.

### ISSUE THREAD

**Issue by ivanmaia** [colindembovsky/cols-agent-tasks#147]
Some source control tools such as Git work better when files end with an empty line.

Some code quality tools such as SonarQube will create an issue if there is no empty line at the end of the file.

I have a json file that has an empty line at the end, but the task removes that empty line.

It would be nice if the task simply leaves that empty line there.

Thanks a lot.

**Comment by colindembovsky** [comment]
Hi @ivanmaia - you could easily add an empty line using an inline task following the `replaceToken` if needed: something like this:

```
script: printf "\n" >> file.txt
```
