### ISSUE TITLE
Cannot see deploymentReport.md in Azure Devops Pipeline after comparison 

### ISSUE THREAD

**Issue by coding-totoro** [colindembovsky/cols-agent-tasks#156]
Hi, 

deploymentReport.md is available on the hosted agent in the work folder. However we cannot see this in the azure portal, is there a way to output the results to the job/task step?

**Comment by Calumfletcher** [comment]
Hi @coding-totoro , just spotted your question whilst asking one myself.

For me, the report is available by going to your build pipeline -> clicking a successful build -> clicking 'Extensions' tab

![image](https://user-images.githubusercontent.com/49764991/91199326-a6eac080-e6f5-11ea-8428-00581ff29cfe.png)

Hope this helps
Cheers

**Comment by coding-totoro** [comment]
Doh! Thank you!
