### ISSUE TITLE
TokenReplace: Cannot replace a token with an empty value

### ISSUE THREAD

**Issue by mikebranstein** [colindembovsky/cols-agent-tasks#16]
When running the replace tokens task, if a release variable exists, but is an empty string, the token replace fails. Some of our environments have configuration values that are not required, but are required in others, so we leave the value blank.

**Comment by colindembovsky** [comment]
I can't seem to repro this. Can you provide a full log please?

**Comment by mikebranstein** [comment]
Thanks, Colin.

This can be closed. After looking closer, it's really a limitation of TFS/VSTS. A release variable must have a value assigned if it's defined for an environment. We've gotten around the issue by placing a space " " in the value for the release variable. This works "ok".

Unfortunately, when you place a space in the release variable, it's value is saved, but when the variables page reloads in TFS, it must be performing a trim() on the textbox value, so it clears out the space. 

I'd consider removing the release variable from our environments that don't need the tokenization; however, our build outputs the __OptionalTokenToReplace__, which does need swapped with an empty string or a space during the Replace Tokens task.

Ideally, I'd like to tell TFS that a release variable can be an empty string. An alternative would be another task/way to clear the value in SetParameters.xml.

What I think we're really going to do is define a value for the release variable like "null" and change our code to look for that value.

**Comment by colindembovsky** [comment]
Perhaps you could have a couple versions of your SetParameters.xml file? One for the "full set" of variables and one for a "scaled down set" of variables? Then just use the appropriate one in the deployment.
