### ISSUE TITLE
Version Assemblies: Whitespace in Source Path

### ISSUE THREAD

**Issue by dweyermann** [colindembovsky/cols-agent-tasks#17]
Version Assemblies task does't seem to respect whitespaces in the "Source Path", e. g.:
- Source Path:  _$/Omega/ABC Manager.Droid/Properties_
- File Pattern: _AndroidManifest.xml_

This will produce the following log:
 ##[debug]glob "C:\a\1\s\ABC Manager.Droid\Properties"\AndroidManifest.xml
 ##[debug]found 0 matches
 ##[warning]No files found

**Comment by colindembovsky** [comment]
@dweyermann Thanks for reporting - I've fixed this.
