### ISSUE TITLE
Tag Build or Release 'A supported task execution handler was not found.' error on TFS 2018

### ISSUE THREAD

**Issue by pm90pl** [colindembovsky/cols-agent-tasks#180]
Task: Tag Build or Release
Version      : 0.1.152
TFS 2018
Agent ver. 2.136.1

After upgrade from ver 0.1.114 to the current (0.1.152) following error occurs on Tag Build or Release task:
A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows'. Contact the task author for more details.

The tasks were upgraded to Node10 - this version is available since agent ver 2.144. In that case, an additional requirement should be added:
"minimumAgentVersion": "2.144.0"

Source: http://blog.majcica.com/2018/12/04/node10-provider-available-for-agent-v2-144-0/

**Comment by WoodyWoahzay** [comment]
Same issue as above.

**Comment by spangeman** [comment]
Getting the same issue, is there a way to revert back to using 0.1.114 somehow while we wait for a fix?

**Comment by TudorPrunici** [comment]
I have the same problem in all projects.

**Comment by WoodyWoahzay** [comment]
Does anyone have a workaround or can recommend a different extension to use?

**Comment by Sacrilege** [comment]
I can confirm that upgrading the agents fixes the issue.

**Comment by TudorPrunici** [comment]
> Getting the same issue, is there a way to revert back to using 0.1.114 somehow while we wait for a fix?

how do i make it? i don't find this in tfs

**Comment by spangeman** [comment]
> 

How did you update the agent?

**Comment by spangeman** [comment]
> Sacrilege commented 2 days ago
> I can confirm that upgrading the agents fixes the issue.

How did you update the agent?

**Comment by spangeman** [comment]
I can also confirm updating your build agent fixes this issue. Note that if you are on TFS 2018 and try to use the Download link within TFS for updating the agent you will get an out of date agent. You need to use https://github.com/microsoft/azure-pipelines-agent/releases.

Also note that you may have separate agents for your build and release, they will both need to be updated. You can see which version of the agent is running in your build and/or release logs at the very start of the log text.

**Comment by colindembovsky** [comment]
Thanks @spangeman for the confirmation. I upgraded to `Node10` runner because the older runner is deprecated. Didn't know that the TFS 2018 agents were "old" - but to be fair, that's a server version that's 4 years old now!
