### ISSUE TITLE
##[error]A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.

### ISSUE THREAD

**Issue by KishoreCFN** [colindembovsky/cols-agent-tasks#183]
getting below error while using Tokenize Files tasks ##[error]A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.

**Comment by colindembovsky** [comment]
Hi @KishoreCFN - Are you on TFS 2018 by any chance? See this thread for a similar issue. https://github.com/colindembovsky/cols-agent-tasks/issues/180#issuecomment-984758533

**Comment by KishoreCFN** [comment]
Yes we are using TFS 2018. I did upgrade the Agents to the latest version. Error is gone But config files are not getting tokenized.

**Comment by KishoreCFN** [comment]
Resolved the issue by  upgrading TFS 2018 Build Agent  to v2.195.2 version.

**Comment by KishoreCFN** [comment]
Resolved the issue by upgrading TFS 2018 Build Agent to v2.195.2 version.
