### ISSUE TITLE
Bump up the version number.. Possible?

### ISSUE THREAD

**Issue by rahulrulez** [colindembovsky/cols-agent-tasks#19]
Hi Colin,

I am using your extension in one of my build definitions. I have Build number formatting `1.0.0$(rev:.r)`. 

The plugin picks up `d+` from the last revision of build number if I am not wrong. How do we handle the version bump i.e. `1.0.0.1` to `2.0.0` or `2.0.0.1` for my app (in case of total revamp etc).

How can I do that? I am quite confused. Is there any provision for that?

**Comment by colindembovsky** [comment]
@rahulrulez I normally do that manually - as you mention it's the case for a total revamp or major change. Just change the build version format of the build itself to 2.0.0($rev.r) or whatever.

**Comment by rahulrulez** [comment]
Cool, is there any way you know of automating it?

**Comment by colindembovsky** [comment]
@rahulrulez How would you automate it? How would the build know when to increment the major version? You could implement your own versioning via script and using the ##[vso] logging - but this shouldn't be happening regularly enough to warrant automation. If it is, you have other issue :-)
