### ISSUE TITLE
Task definitions require agent version (1.91.0) higher than TFS2015 Update 1 (1.89.1)

### ISSUE THREAD

**Issue by neoKushan** [colindembovsky/cols-agent-tasks#2]
The latest agent version for TFS 2015 Update 1 (Latest as of this post) is 1.89.1, however the tasks here require an agent version of 1.91.0 (Presumably in line with VSO).

This means these tasks cannot currently be used with on-premise TFS installations.

**Comment by colindembovsky** [comment]
I haven't tested these with TFS yet. If you download the tasks and change the version requirement, do they work? If you let me know that they do I will change the agent requirements - otherwise you'll have to wait till I can spin up a TFS instance to test on :-)

**Comment by SamAlavi** [comment]
Hi Colin - Tried your suggestion and didn't work out. It's not about agent version only, it requires TS handler to execute the task which apparently is not shipped with agent v1.89.1. Probably have to wait for Update 2 and give a new shot.

**Comment by colindembovsky** [comment]
@SamAlavi I've successfully run these on TFS 2015 Update 2, so I'm closing this issue.
