### ISSUE TITLE
ReplaceTokens toLowerCase error

### ISSUE THREAD

**Issue by jerry2007** [colindembovsky/cols-agent-tasks#20]
Hello I have a problem with Replace Tokens Task on Mac Build Agent...
The build in vsts raise error when replacing tokens...

Unhandled: Cannot read property 'toLowerCase' of undefined

Can you help me pls??

**Comment by colindembovsky** [comment]
hi @jerry2007 

Can you please paste the full log for the task?

**Comment by brunomolina** [comment]
sou obrigado a falar
