### ISSUE TITLE
ReplaceTokensTask: Cannot read property 'split' of null 

### ISSUE THREAD

**Issue by mieliespoor** [colindembovsky/cols-agent-tasks#22]
Since you updated this task today, we are getting the error "Cannot read property 'split' of null " if we do not specify any value for the 'secretTokens' property.

This happens on line 15 with the undefined check:
`if (typeof secretTokenInput !== "undefined") {`
 
All I did was to add a null check before to get our releases going again.

`if (secretTokenInput != null && typeof secretTokenInput !== "undefined") {`

Not sure if this is 100% correct, but it got our releases going, so that is all that mattered for me.

**Comment by colindembovsky** [comment]
Thanks @mieliespoor - I updated the task to use the new vsts-task-lib in preparation for the new .NET Core agent - and it handles empty parameters differently than the old vso-task-lib did. I've fixed it in extension version  0.1.32. Let me know if it works for you!

**Comment by colindembovsky** [comment]
And as a bonus it seems that the secret tokens are passed into the Node version of the tasks now "ambiently" so I'll be able to drop the SecretTokens input hack! Whoop!

**Comment by mieliespoor** [comment]
@colindembovsky ; Thanks, I did a release with the updated version and it seems to work.
