### ISSUE TITLE
Dacpac report Task - Cannot find path because it does not exist

### ISSUE THREAD

**Issue by GuruCharan94** [colindembovsky/cols-agent-tasks#26]
I am copying my dacpac to stagingdirectory/dacpac and publishing it as artifact in build definition.   

## Screenshot of task
https://drive.google.com/file/d/0B9i7hBHv-vrtVVFmMUtCVll2NWM/view?usp=sharing   

## **Logs** 

Line 1 : 2016-08-20T10:43:33.3657395Z ##[debug]Using sqlPackage path C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130\SqlPackage.exe  

**2:** 2016-08-20T10:43:33.5615345Z ##[debug]Found build @{_links=; plans=System.Object[]; id=186; buildNumber=20160820.11; status=completed; result=succeeded; queueTime=2016-08-20T10:25:59.5985544Z; startTime=2016-08-20T10:26:02.559936Z; finishTime=2016-08-20T10:30:02.6561743Z; url=https://agileguru.visualstudio.com/07aab20c-d4f0-4164-a801-ff94df9636fc/_apis/build/Builds/186; definition=; buildNumberRevision=11; project=; uri=vstfs:///Build/Build/186; sourceBranch=refs/heads/Dev; sourceVersion=7ce7fe2005ad99e3195ec2cbf4cfdb4aad07eac9; queue=; priority=normal; reason=manual; requestedFor=; requestedBy=; lastChangedDate=2016-08-20T10:30:04.367Z; lastChangedBy=; parameters={"system.debug":"false","BuildConfiguration":"release","BuildPlatform":"any cpu"}; orchestrationPlan=; logs=; repository=; keepForever=False; retainedByRelease=False} for compare   

**3:** 2016-08-20T10:43:33.6235342Z ##[debug]Downloading drop https://agileguru.visualstudio.com/07aab20c-d4f0-4164-a801-ff94df9636fc/_apis/build/builds/186/artifacts?artifactName=Dacpac&%24format=zip  

**4**:2016-08-20T10:43:45.8649529Z ##[debug]Expand-Archive does not exist. Using System.IO.Compression.ZipFile 

 **5:**2016-08-20T10:43:46.0269528Z ##[error]Cannot find path 'C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.104.1\tasks\DacPacReport\0.0.1\SourceDrop' because it does not exist.

**Comment by GuruCharan94** [comment]
Went through the logs and the source code and played around with **Powershell for the first time** and I think **Pull Request #27** will help fix the issue..

**Comment by colindembovsky** [comment]
Fixed this in PR https://github.com/colindembovsky/cols-agent-tasks/pull/29
