### ISSUE TITLE
Missing vso-task-lib running in VSTS Release Management

### ISSUE THREAD

**Issue by markphillips100** [colindembovsky/cols-agent-tasks#3]
I'm using the ReplaceTokens task in a simple release definition in VSTS.  It's configured exactly as the task's readme describes.

I receive the following log output which complains of a missing vso-task-lib. I've seen (but not used) a [vsts-task-lib](https://github.com/Microsoft/vsts-task-lib) and was wondering if that is the library tasks should consume now?  If so can we get a new extension deployed to VSTS soonish?

Log output:
`2016-02-04T21:46:03.7720831Z Set workingFolder to default: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\ReplaceTokens\0.0.3
 2016-02-04T21:46:06.6180311Z module.js:338
 2016-02-04T21:46:06.6180311Z     throw err;
 2016-02-04T21:46:06.6180311Z           ^
 2016-02-04T21:46:06.6180311Z Error: Cannot find module 'vso-task-lib'
 2016-02-04T21:46:06.6180311Z     at Function.Module._resolveFilename (module.js:336:15)
 2016-02-04T21:46:06.6180311Z     at Function.Module._load (module.js:278:25)
 2016-02-04T21:46:06.6180311Z     at Module.require (module.js:365:17)
 2016-02-04T21:46:06.6180311Z     at require (module.js:384:17)
 2016-02-04T21:46:06.6180311Z     at Object.<anonymous> (C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\ReplaceTokens\0.0.3\replaceTokens.js:1:72)
 2016-02-04T21:46:06.6180311Z     at Module._compile (module.js:460:26)
 2016-02-04T21:46:06.6180311Z     at Object.Module._extensions..js (module.js:478:10)
 2016-02-04T21:46:06.6180311Z     at Module.load (module.js:355:32)
 2016-02-04T21:46:06.6180311Z     at Function.Module._load (module.js:310:12)
 2016-02-04T21:46:06.6180311Z     at Function.Module.runMain (module.js:501:10)`

**Comment by dixu99** [comment]
I copy the content in the node_modules folder in the root folder into Tasks\ReplaceTokens\node_modules and reupload the task. It works fine after that.

**Comment by colindembovsky** [comment]
I've updated the task packages.json files to include the vso-task-lib. Then I just run `npm install` in each task folder to install the package and re-uploaded the extension.

Thanks for reporting the issue!

**Comment by mieliespoor** [comment]
I am also getting this error. I don't really want to waste time customizing the task. How can I get this working?

**Comment by colindembovsky** [comment]
Hi @mieliespoor If you install this task via the [Marketplace](https://marketplace.visualstudio.com/items?itemName=colinsalmcorner.colinsalmcorner-buildtasks) you'll get the latest version that doesn't have this issue. You'll also get automatic updates etc.

**Comment by mieliespoor** [comment]
Hello, that is where I got the task. I opted for the marketplace version for update reasons...

**Comment by colindembovsky** [comment]
@mieliespoor which version of TFS are you using? Or are you on VSTS? Can you please include the full build log (sanitized if necessary)?

**Comment by mieliespoor** [comment]
VSTS.

It failed using a hosted agent and also tried a local agent. The attached logs is for the local agent
[ReleaseLogs_50.zip](https://github.com/colindembovsky/cols-agent-tasks/files/227337/ReleaseLogs_50.zip)

**Comment by colindembovsky** [comment]
@mieliespoor I can't repro this - version 0.0.15 of the task runs just fine for me.

Thanks for the logs. Can you have a look in this folder: `F:\tfa1\tasks\ReplaceTokens\0.0.15` and see if there is a `node_modules` folder?

**Comment by mieliespoor** [comment]
There wasn't. I copied it there myself from another task to try and see if I van get it working. Still the same result.

**Comment by colindembovsky** [comment]
@mieliespoor Hmm that's strange. Can you delete the folder totally and let the agent re-download the Task?

**Comment by mieliespoor** [comment]
Yes the task got corrupted, or rather stuck. I deleted the extension and the task still showed up in my list or when I ran. `tfx build tasks list.`

I then manually deleted the task using tfx and installed the extension again. I did delete the extension yesterday, but never saw the task somehow got left behind.

The task now runs as expected.

**Comment by colindembovsky** [comment]
Thanks @mieliespoor! Glad you're unstuck.
