### ISSUE TITLE
Recursive file search

### ISSUE THREAD

**Issue by peterM** [colindembovsky/cols-agent-tasks#32]
Hi. 

I have problem to handle this situation.
When i building solution i use buildNumber as folder name so i have structure like this:

drop\Folder\Folder_{XXX}\app.config
Where XX is dynamic numbering.

When i am releasing i am using your task to replace tokens. I do not know how to navigate to 'Folder_XX'
Please can you implement scenario to set start folder (current example drop\Folder\) from where will token replacer search all files defined in box 'Target file pattern'

Thanks for your help.

**Comment by peterM** [comment]
I created pull request #33 
PM.

**Comment by colindembovsky** [comment]
Hi @peterM - the "Target File Pattern" already supports MiniMatch, which means you can specify `drop\Folder` for the Source Path and `**\app.config` for the Target File Pattern. The `**` will match any subdir in the Source Path, so it should work on dynamic folders (like your build number). Can you try that before I look at the PR?

**Comment by peterM** [comment]
Hi. Nice to know.
Honestly I did not know about this matching pattern.
I will try it. and let you know.

**Comment by peterM** [comment]
I tried it already and it is working perfectly :) ... 
You can reject PR :) 
Thanks

**Comment by colindembovsky** [comment]
Glad you got it working @peterM
