### ISSUE TITLE
DacPac Change Report Task not in Task List

### ISSUE THREAD

**Issue by gssexton** [colindembovsky/cols-agent-tasks#34]
DacPac Change Report Task looks like a great task.  I am using TFS 2015.3 and just added Colin's ALM Corner Custom Build Task v1.1.40.  I edit my build definition and try to add the task but in to not in the list of available tasks.

I have performed an update, uninstalled and reinstalled but still no luck.  Any ideas?

Thanks

**Comment by colindembovsky** [comment]
Hi @gssexton - can you try with 1.1.41 - I had a minimum agent requirement that looks like it blocked the install. I've reverted the version in 5d3260529f6613eed35cbc8070e6268f883407e2 to see if that at least installs the task. I think this is a bug with tfx - the task should upload irrespective of the agent version.

**Comment by colindembovsky** [comment]
Seems like this is expected behavior (the task is not uploaded) - unfortunately the error is silent in TFS 2015.3 and earlier. Later versions of TFS will surface an error message.

**Comment by gssexton** [comment]
Thanks for the quick turnaround.  The task is now showing up in the list.

Geoff
