### ISSUE TITLE
Virus warning

### ISSUE THREAD

**Issue by tschissler** [colindembovsky/cols-agent-tasks#37]
When I download the repro as a ZIP I get this message from Windows Defender, anyone else?

Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items: 
containerfile:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\7C3ABA63-688B-0EE1-2B8A-09AD80F61ECB_1d25198276f6eb9
containerfile:C:\Users\tschi\Downloads\cols-agent-tasks-master.zip
file:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\7C3ABA63-688B-0EE1-2B8A-09AD80F61ECB_1d25198276f6eb9->(MPLC)->cols-agent-tasks-master/Tasks/CoverageGate/coverageGate.js
file:C:\Users\tschi\Downloads\cols-agent-tasks-master.zip->cols-agent-tasks-master/Tasks/CoverageGate/coverageGate.js
webfile:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\7C3ABA63-688B-0EE1-2B8A-09AD80F61ECB_1d25198276f6eb9|https://codeload.github.com/colindembovsky/cols-agent-tasks/zip/master|browser_broker.exe
webfile:C:\Users\tschi\Downloads\cols-agent-tasks-master.zip|https://codeload.github.com/colindembovsky/cols-agent-tasks/zip/master|browser_broker.exe

**Comment by colindembovsky** [comment]
I'm unable to repro this @tschissler - when I scan with Defender I get a clean bill of health. If you clone the repo and scan the folder do you get the same warning? I can't find browser_broker.exe (or any other exe) in the repo either.

**Comment by tschissler** [comment]
Strange, Windows Defender has nothing against the download today. Not sure what tis was but it seems not to be an issue with the repro itself. Sorry for bugging around here.
