### ISSUE TITLE
Not replacing $(Build.BuildNumber) 

### ISSUE THREAD

**Issue by lcmassena** [colindembovsky/cols-agent-tasks#47]
I'am trying to replace some variables but it's not working.

This is my javascript file

`angular.module('app')
.service('Configs', [function () {
    this.App = {
        Id: "xxxxx",
        Name: "xxxxx",
        Version: "__$(Build.BuildNumber)__",
        VersionDate: "__$(Day:dd)__/__$(Month:MM)__/__$(Year:yyyy)__",
        BaseUrl: window.location.origin + "#/",
        Services: { Backend: { ServiceURL: "__ApiUrl__", }} ////ApiUrl is replaced during release
    };
}]);`

I also tryed the following using a variable **Version** with value **$(Build.BuildNumber)**, and still not working:

`angular.module('app')
.service('Configs', [function () {
    this.App = {
        Id: "xxxxx",
        Name: "xxxxx",
        Version: "__Version__",
        VersionDate: "__VersionDate__",
        BaseUrl: window.location.origin + "#/",
        Services: { Backend: { ServiceURL: "__ApiUrl__", }} ////ApiUrl is replaced during release
    };
}]);`

What I am doing wrong?

**Comment by colindembovsky** [comment]
Hi @lcmassena - can you please set a variable `system.debug` and set the value to `true`. Then post the logs for this task so that I can look at them?

**Comment by colindembovsky** [comment]
Closing due to lack of response. @lcmassena feel free to open again if you need to.
