### ISSUE TITLE
Task definition with id is a built-in task definition and cannot be replaced.

### ISSUE THREAD

**Issue by LockTar** [colindembovsky/cols-agent-tasks#54]
I get this error when I want to enable the extention in a TFS2017 Update 1 collection.
Any ideas?

**Comment by colindembovsky** [comment]
Hi @LockTar 

Can you please run tfx build tasks list and then trim it to a list of Task ids. Seems like there's an id collision somewhere. You can check the task Ids from my extensions in this source repo (check the task.json files).

**Comment by LockTar** [comment]
Hi Colin,
I know what the issue is. 
Apparently other administrators installed an old version of your "assembly versioning" manually when TFS2015 was released. So now there is of course a collision with the new version. 

We are not able to manually remove the old version (and install the extension from the marketplace) because that will give a breaking change. This because the new version 2 is using a different "Version Extract Pattern". 
What we can do is install an old version of the extension which doesn't have the "Version Extract Pattern" option but "Build Regex Pattern" to "\d+\.\d+\.\d+\.\d+".
After we installed that version of the extension we can update the extension to the latest version. In that way, people can change the version of the task it self in the right upper corner of the task in the build definition. 

Do you have a place where I can download an old version of the extension with version 0.* inside?

**Comment by colindembovsky** [comment]
Hi @LockTar - I don't have an old copy of the extension. However, you can clone this repo, checkout this commit [aef8af](https://github.com/colindembovsky/cols-agent-tasks/commits/aef8af213523ca30f7876752de5892a6e0e61bed) and then upload the task using `tfx`.

So do the following:
```
git clone https://github.com/colindembovsky/cols-agent-tasks
git checkout aef8af
cd Tasks\VersionAssemblies
npm install
cd ..
tfx build tasks upload --task-path VersionAssemblies --overwrite
```
You may need to update the version number to match the version number that you have locally (or a +1 on the patch number).

**Comment by LockTar** [comment]
Hi @colindembovsky - I cloned everything and got an even older version of the extension. 
I created the vsix and removed the old task with the cli. I then installed the old vsix and then updated the extension to the latest from the marketplace. We now have 2 versions of the task and is exactly what we want.
Thank you for the help!
