### ISSUE TITLE
VSTS Pull Requests

### ISSUE THREAD

**Issue by 42shadow42** [colindembovsky/cols-agent-tasks#55]
I am attempting to use the Gated Coverage plugin for a gated build. It appears however the plugin compares the build against the source branch, not the target branch when ran on a VSTS pull request. Is there a way to make this use the target branch or a specific branch for historical coverage?

Thanks!

**Comment by colindembovsky** [comment]
Hi @42shadow42 - the task just compares to the last "good" build (that is a build that has completed successfully, not just partially successful). I don't check the _branch_ for the build at all.

**Comment by 42shadow42** [comment]
@colindembovsky Thanks, now that you mention it, it is possible that I didn't have a SUCCESSFUL build with coverage because I just assumed it was checking the source branch because it said I didn't have coverage results to compare against, when I knew there were. I'll try it out again, thanks for the help!

**Comment by CaLxCyMru** [comment]
OK

**Comment by 42shadow42** [comment]
@colindembovsky @CaLxCyMru 

I have several successful builds with coverage, some of which I believe used the coverage gate, but today I got the error again. "There are no coverage deltas. Make sure you have at least 2 builds."

Here is a summary of my build history:

40 hours ago. Build Failed. Code Coverage: 100%.
5 days ago. Build Succeeded. Code Coverage: 100%.
5 days ago. Build Succeeded. Code Coverage: 100%.
5 days ago. Build Failed. Code Coverage: Not Reported.
5 days ago. Build Succeeded. Code Coverage: 100%.
5 days ago. Build Succeeded. Code Coverage: 100%.
5 days ago. Build Succeeded. Code Coverage: 100%.
5 days ago. Build Succeeded. Code Coverage: 100%.

**Comment by colindembovsky** [comment]
Hi @42shadow42 @CaLxCyMru 

Can you set a variable in the release/environment called `system.debug` and set the value to `true`. Then paste the logs from the CoverageGate task. I'll then be able to see what's going on.
