### ISSUE TITLE
Consider changing default regular expression 

### ISSUE THREAD

**Issue by DanHibbert** [colindembovsky/cols-agent-tasks#56]
Would you consider changing the default regular expression for replace tokens from __(\w+)__  to __([a-zA-Z0-9_\.:]+)__ .  Increasingly seeing .net apps (especially azure stuff) using app:setting e.g. ida:ClientId  which the current regex doesn't pick up.

**Comment by colindembovsky** [comment]
Hi @DanHibbert - I think that I'm going to leave the default to `(\w+)` since that's the option for most people currently. Of course this is easy to change, and you can even template this if you really wanted to.
