### ISSUE TITLE
Replace changes the file encode to ASCII

### ISSUE THREAD

**Issue by gocoelho** [colindembovsky/cols-agent-tasks#59]
When i try to replace token from a file with ANSI enconde, after replace it converted to UTF-8. This is very bad for files which contains special characters.

String "Versão"

Before (ANSI)
![image](https://cloud.githubusercontent.com/assets/7503127/26173844/b1cc5080-3b23-11e7-88a3-ca85c7d81643.png)

After (UTF-8)
![image](https://cloud.githubusercontent.com/assets/7503127/26173787/7a6fc5cc-3b23-11e7-8912-b1976185ee95.png)

**Comment by duckwaffle** [comment]
+1

It would actually be much better if you detected the file encoding before opening the text file, and then saved back using the same encoding. We were stuck for a few hours because of the "Utf-8 only" issue.

**Comment by colindembovsky** [comment]
I think I've fixed this in 1.1.169 - can @gocoelho and @duckwaffle please confirm?
