### ISSUE TITLE
Encrypted Password

### ISSUE THREAD

**Issue by tadzik96** [colindembovsky/cols-agent-tasks#63]
Hi, is there a way to Replace the Password token in the connection string so that it will be encrypted as ******? (In my setParameters file i have the password argument showing as normal i want to be encrypted)

**Comment by colindembovsky** [comment]
If you're on VSTS (or TFS 2017), you can define multiple parameters and use expansion. For example:

Variable | Value
--- | --- |
username | bob
server | myServer
dbName | myDb
password | *****
conStr | Data Source=$(server); Initial Catalog=$(dbName); Username=$(username); Password=$(password)

And that will give you the desired effect!

**Comment by tadzik96** [comment]
Hi, That sorted it. i Have another question in my setParameters.xml My connection string changes but when i try to access the web page With IIS my connection string looks lik this __ConnectionStr__ 
![image](https://user-images.githubusercontent.com/23195956/26920258-58ee699e-4c30-11e7-8e90-e31c3a21146f.png)
And then i Get the error : 

[Organization cannot be null or empty.
Parameter name: Organization Name 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.ArgumentNullException: Organization cannot be null or empty.
Parameter name: Organization Name

Source Error: 


 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  
](url)

**Comment by colindembovsky** [comment]
Hi @tadzik96 - looks like you're deploying to IIS. How are you doing that? If you're using the WinRM IIS task, then remember to do the replace on the agent, then copy the zip file and SetParameters file to the target server and then invoke the IIS task.

Can you also check the logs for the ReplaceToken task and ensure that it's not outputing any warnings - if the environment variable isn't defined, then the task will warn. I assume you have a variable called `CrmConnectionString` (no underscores) with the value.

**Comment by tadzik96** [comment]
Hi @colindembovsky Yes i am using the WinRM IIS task, I dont know what u mean by replacing the agent(Sorry i am a newbie to all of this), I am creating a temp folder then I copy the Zip and all the associated files into the temp folder and the i run the manage and deploy Task. These are the steps im using 
![image](https://user-images.githubusercontent.com/23195956/26967233-68ca60e6-4cf5-11e7-8b9e-77fedad25a9f.png)


I am getting this error : Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by tadzik96** [comment]
When i try to browse the website It gives me this error : I am getting this error : Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by colindembovsky** [comment]
Hi @tadzik96 - you have to do the ReplaceTokens task before the copy since this task works on files on the agent. Then when you copy the zip and SetParameters files to the target server, the SetParameters file will contain the correct values, so that the IIS task deploys them correctly.

**Comment by tadzik96** [comment]
Nice! I loved your turtorial it helped me very much Thanks! Keep up the Good work! :)
