### ISSUE TITLE
Variables and Data Types

### ISSUE THREAD

**Issue by rashidbpg** [colindembovsky/cols-agent-tasks#64]
Hi, we are replacing tokens in a JSON configuration file and one of the properties expect a boolean. The issue is that when the token is replaced, it is being set as a string (i.e. "false") rather than false. We can possible change the code to correctly parse, but rather not. Is there a way to specify a data type to replace it?

**Comment by colindembovsky** [comment]
Hi @rashidbpg - nope, I don't have this in yet. I'll look into this to see what I can do - but I'll accept PRs too :-)!
