### ISSUE TITLE
Tokenizer fails on JSON comments

### ISSUE THREAD

**Issue by andrasg** [colindembovsky/cols-agent-tasks#71]
I am trying to tokenize a json that contains `/* comment */` and `// comment ` style comments. Tokenize fails though:
```
Unexpected token / in JSON at position 1090
```
Would be nice if tokenize would handle comments.

**Comment by colindembovsky** [comment]
Hi @andrasg - Unfortuntately I can't do much about this. I'm reading the json in using `JSON.parse()` and it doesn't do comments because _comments are not valid JSON_. That's why a lot of json schemas have `"_comments"` properties (or some other mechanism that is valid JSON).
