### ISSUE TITLE
Tokenizer replaces CRLF

### ISSUE THREAD

**Issue by andrasg** [colindembovsky/cols-agent-tasks#72]
When running on a Windows agent, Tokenizer uses CR instead of CRLF (originally in the file). When opening a file output by Tokenizer in Notepad, it won't show any linebreaks. This heavily decreases readability.

**Comment by colindembovsky** [comment]
Hi @andrasg I will take a quick look to see if `JSON.stringify()` takes any settings that will preserve line endings. If you can suggest any that would be great!
