### ISSUE TITLE
tokenize multiple file specs

### ISSUE THREAD

**Issue by userjeff3** [colindembovsky/cols-agent-tasks#73]
Back in July, in the user reviews on the marketplace web site, you suggested I use "* .{config,nuspec}" for the replace tokens target file pattern, which worked great. Until yesterday, when it suddenly started generating the error "Could not find files with glob [* .{config,nuspec}]". There were no changes to anything else whatsoever, as this is a mature pipeline. When I changed it to "*.+(config|nuspec)", it started working again, so no real problems, but perhaps this should be added to the documentation.

But I just can't imagine why a TFS extension might suddenly change its behavior. Could it have updated itself?

Thanks!

**Comment by colindembovsky** [comment]
Likely the VSTS API changed. I use the task library for the find files function. I'll take a note to update the docs.
