### ISSUE TITLE
Null locationUrl tagging release on TFS 2017.2

### ISSUE THREAD

**Issue by llykke** [colindembovsky/cols-agent-tasks#76]
Hi Colin
Thank you very much for this extension! :-)
We're getting on our way to promote our builds/releases via tagging but are experiencing the error below when trying to apply a tag in a release definition on a release:

`(node:3652) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'locationUrl' of null`

There is no further output from the task in the console view apart from the 'task header' and the above error message.

I believe it's from [this line of code](https://github.com/colindembovsky/cols-agent-tasks/blob/d059cc315990003c5faaf65da3dc5be483446640/Tasks/TagBuild/tagBuild.ts#L84)
`let releaseApi = vsts.getReleaseApi(releaseResourceArea.locationUrl);`

We're using TFS 2017 update 2 (on-premise with private agents), which I believe have a different API as compared to current VSTS?

If I try tagging the primary build artifact instead, I don't get any errors and build is tagged as expected.

**Comment by Jay-Harlow** [comment]
I'm getting the same error, also on TFS 2017 update 2 on-premise.

**Comment by colindembovsky** [comment]
Hi @llykke - thanks for reporting. I'll have a look at this in the next couple days.

**Comment by colindembovsky** [comment]
@llykke and @Jay-Harlow Can you guys please try the latest release (1.1.174) and let me know if the task works?

**Comment by llykke** [comment]
I can confirm, that with release 1.1.174 I am now able to tag a release, from within the same release.
This is using TFS 2017 update 2 (on-premise). 
The build tagging of the primary artifact also (still) works as expected.

I've only tested applying a single tag. I've not tested with multiple tags.

Thank you! :-)

**Comment by colindembovsky** [comment]
Thanks @llykke for the confirmation!
