### ISSUE TITLE
Update only part of version number in AssemblyInfo file?

### ISSUE THREAD

**Issue by deadlydog** [colindembovsky/cols-agent-tasks#78]
I'm looking to use semantic versioning in our application, where we would be manually updating the version number in source control, and then just have the VSTS build update the revision (4th part of the version number) so that the version number is unique, likely by using [the $(Rev:r) VSTS Build variable](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/options#build-number-format). Is it possible to do that using the Version Assemblies task?

i.e. The ApplicationInfo.cs file has the version `2.3.4.0` defined in it, and I want the build system to update it to `2.3.4.123`

I'm guessing it is possible to do by using some custom regular expressions for the capturing and replacing of the version number, but I'm not certain what the regex would look like for those 2 fields. Any suggestions? Thanks!

**Comment by colindembovsky** [comment]
Hi @deadlydog - how often to you update the first 3 numbers? If you hard-code your build number format to be `2.3.4$(rev:.r)` and use the default `1.0.0.0` format for the VersionAssembly task, you'll get exactly what you want. Of course you'd have to update the build number format whenever you change the other numbers (the 2.3.4 portion) but if you don't do that often, you'll be good to go.

The other option is to do a custom numbering script before VersionAssemblies - but keep the logic out of VersionAssemblies is the point!

**Comment by deadlydog** [comment]
Thanks for the response @colindembovsky. Defining the version number in Build Number Format is an alright solution, especially if there is a team of devs and you just want one person (e.g. project manager or team lead) to be responsible for updating the version number. For personal projects though, I often want to setup my CI/CD pipeline once and then not have to touch it after that, and instead just work purely in code (and update the version number there).

I think having a custom script to update the Build Number Format environmental variable based on the version extracted from the AssemblyInfo.cs file would work, but I never got around to trying it. I found [a different VSTS versioning task](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-Versioning-Task) that supported the functionality I was requesting here and have just switched to that one. Thanks though!
