### ISSUE TITLE
Not finding any matches

### ISSUE THREAD

**Issue by trailmax** [colindembovsky/cols-agent-tasks#8]
After the last update the plugin fails to update the version (everything worked perfectly before). Here is the log:

>Set workingFolder to default: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.96.3\tasks\VersionAssemblies\0.1.15
[debug]Starting Version Assemblies step
[debug]sourcePath=C:\a\1\s\MyProject\MyProject
[debug]check path : C:\a\1\s\MyProject\MyProject
[debug]sourcePath=C:\a\1\s\MyProject\MyProject
[debug]filePattern=AssemblyInfo.*
[debug]buildRegex=\d+\.\d+\.\d+\.\d+
[debug]buildRegexIndex=0
[debug]replaceRegex=
[debug]replacePrefix=
[debug]failIfNoMatchFound=true
[debug]Build.BuildNumber=1.3.2.0
[debug]sourcePath :C:\a\1\s\MyProject\MyProject
[debug]filePattern : AssemblyInfo.*
[debug]buildRegex : \d+\.\d+\.\d+\.\d+
[debug]buildRegexIndex : 0
[debug]replaceRegex : 
[debug]replacePrefix : 
[debug]failIfNoMatchFound : true
[debug]buildNumber : 1.3.2.0
[debug]Using \d+\.\d+\.\d+\.\d+ as the replacement regex
[debug]Using 0 as the build regex index regex
Using prefix [] and version [1.3.2.0] in folder [C:\a\1\s\MyProject\MyProject]
[debug]glob C:\a\1\s\MyProject\MyProject\AssemblyInfo.*
[debug]found 0 matches
[warning]No files found
[debug]Leaving Version Assemblies step

AssemblyInfo.cs file is a standard file, not been changed from day zero. 

Also flag `failIfNoMatchFound` is set, but the flag does not do anything - the build does not fail, though no match is found.

Thanks

**Comment by trailmax** [comment]
Ah. Fixed it. Had to replace `AssemblyInfo.*` in File Pattern field to be `**\AssemblyInfo.*`. Not really backwards compatible, but more flexible

**Comment by colindembovsky** [comment]
Hi @trailmax. Apologies - I realized that I might have broken some builds for this "not compatible" patch, but it does make the task much more flexible. Apologies that you were affected!

**Comment by trailmax** [comment]
No problem, it indeed makes the task more flexible. I wish there was some sort of universal notification method for all users of a software, to communicate a breaking change.
