### ISSUE TITLE
Authentication error when using Tag Build task

### ISSUE THREAD

**Issue by mayeager22** [colindembovsky/cols-agent-tasks#81]
I am getting the following error when I try to tag a Build from a Release definition.  I am not sure where to enable OAuth in the Build/Release options.  

##[error]Could not find token for autheniticating. Please enable OAuth token in Build/Release Options.

I do have the security set as mentioned in this link (https://github.com/colindembovsky/cols-agent-tasks/tree/master/Tasks/TagBuild)

**Comment by mayeager22** [comment]
I did find the "Allow Scripts to Access OAuth Token" on the build definition and it was already checked.

Is there a similar option on the Release definition, because I don't see an Options tab.

**Comment by mayeager22** [comment]
Found it: https://stackoverflow.com/questions/41004090/vsts-allow-scripts-to-access-oauth-token-in-release-managment

**Comment by colindembovsky** [comment]
Hi @mayeager22 - glad you got it sorted!
