### ISSUE TITLE
Error in TFS 2015 update 3 - There is no drop with the name drop.

### ISSUE THREAD

**Issue by inehme** [colindembovsky/cols-agent-tasks#83]
I am getting the below error in my TFS build:

Starting task: DacPac Schema Compare ASC.NewProject.Schema.dacpac
******************************************************************************
There is no drop with the name drop.
Got 
Cannot bind argument to parameter 'Path' because it is an empty string.
******************************************************************************
Finishing task: DacPacReport
------------------------------------------------------------------------------
My build definition consists of 
1- Visual Studio Build
2- Copy Files to: $(build.artifactstagingdirectory)
    - Source Folder: $(build.sourcesdirectory)
    - Contents: **\bin\$(BuildConfiguration)\**
    - Target Folder: $(build.artifactstagingdirectory)
3- Publish Artifact: drop
   - Path to Publish : $(build.artifactstagingdirectory
   - Artifact Name : drop
   - Artifact Type : Server
4- DacPac Schema Compare ASC.NewProject.Schema.dacpac
   - Drop Name: drop
   - DacPac Name: ASC.NewProject.Schema
   - Compiled DacPac Path: $(build.artifactstagingdirectory)\bin\$(BuildConfiguration)

Is there something wrong with the above build definition tasks?

**Comment by colindembovsky** [comment]
I have not tested this task in TFS 2015. I can't see anything wrong with what you're doing, but this does work on VSTS. Perhaps there is a difference in the REST API for TFS 2015?
