### ISSUE TITLE
Compare DACPAC to Server

### ISSUE THREAD

**Issue by bbakermmc** [colindembovsky/cols-agent-tasks#84]
Why isnt there a way to compare the drop dacpac to a DB on the server?  I already should know what has changed from build to build.  I need to know what WILL change if I deploy on the server though.

**Comment by colindembovsky** [comment]
My assertion is that the only way you should be deploying is via dacpac - if that's the case then you can tell at build time what is going to change to let you decide if you want the release to go through. Of course if you're changing the db in other ways, this doesn't work.

**Comment by bbakermmc** [comment]
Just because that's "your" method doesn't mean its correct.
I think I have a work arround to just create a DACPAC with the SqlPackage.exe of the DB I want to compare against and use that as the compare DacPac.

Why not have an option to allow two dacpac locations then do the compare that way.  This would allow for any possible combination of compares if people dont want to compare build to build which I assume most people dont.  They want to compare pac1 vs pac2 on UAT, DEV, PROD to see if there ARE any unknown changes.
