### ISSUE TITLE
Create seperate task to do the XML to MD and Upload

### ISSUE THREAD

**Issue by bbakermmc** [colindembovsky/cols-agent-tasks#85]
Create a separate task that will allow for us to make our own PowerShell compare XML and then just upload the MD to VSTS.  Just have two inputs the path for the two XML files.

**Comment by colindembovsky** [comment]
You can do this yourself using [logging commands](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) - no need to add this as a special task (see `##vso[task.uploadsummary]local file path`. That's exactly what I do in the compare task.

I'm curious what you're doing that the task is not doing?

**Comment by bbakermmc** [comment]
Im trying not to rewrite an entire task to do what I want which is to compare two dacpacs and upload the output files to VSTS.  Your Compare task is close, but doesnt allow for me to just say use Pac1 and Pac2 in these locations.

**Comment by bbakermmc** [comment]
How do I test what I changed?

**Comment by colindembovsky** [comment]
I had a look at your PR. It's not what I want this task to be. I'd suggest you just create a PowerShell task to do the compare of 2 arbitrary dacpacs.
