### ISSUE TITLE
Tag Cross-Project Build on Release Errors

### ISSUE THREAD

**Issue by T-Burnius** [colindembovsky/cols-agent-tasks#88]
Great tools! Works great for tagging a release but we have our builds in a separate project.

https://github.com/colindembovsky/cols-agent-tasks/blob/ab91fc9ad713fe1b8ceaafcdb9cc5741c8029661/Tasks/TagBuild/tagBuild.ts#L24

If used in a release, the System.TeamProject variable is tied to the project that the release is created under.

Since my build is contained in a different project from the release, the addbuildtags function call on line 73 fails with: ##[error]TypeError: Cannot read property 'join' of undefined

I think using Build.ProjectName will support cross-project functionality for builds, but it should stick with System.TeamProject for releases.

**Comment by colindembovsky** [comment]
Thanks @T-Burnius for pointing this out. Just when you think you've thought of all the scenarios... I've fixed this in 1.3.14 in this commit: 1bf44ea931659d4b63b92c764dc16015bff6982e
