### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by mariotomek** [colindembovsky/cols-agent-tasks#91]
Hi!

Once the build is completed, I need to create a tag for the build. So I installed this extension into TFS in our company. I created a simple build definition only with the task of creating a tag (Tag Build). In build definition on the tab Options is enabled "Allow scripts to access OAuth token". When I run this build, the task "Tag Build" returne error:
"Error: unable to verify the first certificate".

Can you help me please with this issue?

**Comment by colindembovsky** [comment]
This is likely similar to #94. Can you try the gist in there and let me know if that resolves your error?
