### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by MilkyWare** [colindembovsky/cols-agent-tasks#94]
Hi,

Our onprem TFS has recently had HTTPS enabled and the "Tag Build" task is now causing the builds to fail. The certificates have been installed on the build agent servers and so git can now download the sources, however this task now fails with "Unable to get local issuer certificate".

Any help or ideas would be appreciated

**Comment by axdiamond** [comment]
This is likely an issue with the way your corporate firewall is setup. You'll need to supply Node (which the vsts task runner is built on) with a path to your internal CA certificate.  

Ive fought this issue alot, so I laid out my steps in a gist here
https://gist.github.com/axdiamond/5dc61d54f65b3df413ee0460047cf52f

**Comment by colindembovsky** [comment]
Thanks @axdiamond - I've not run this on a corp network, so I've never been able to repro!
