### ISSUE TITLE
Cannot figure out how to install, build and test

### ISSUE THREAD

**Issue by nphmuller** [colindembovsky/cols-agent-tasks#95]
In your build descriptions you describe the following steps:
```
1. Run `gulp build` to transpile.
2. Run `gulp test-cover` to run tests.
```

However I run into 2 problems when executing these steps.
- The first one is when running any Gulp command I get the error `Local gulp not found in C:\Dev\cols-agent-tasks`. Try running: `npm install gulp`.
This is easily solved by running `npm install gulp`, but I can't shake the feeling that this shouldn't be necessary and that I'm doing something wrong.
- The second error is (after installing gulp): `No gulpfile found` and I'm stumped on this one.
Are the build instructions perhaps outdated? Shouldn't I use Gulp?

I apologise if this is a stupid question, but I simply don't have much experience with Gulp and this problem is stopping me from making a contribution. I would really like to run my tests locally before submitting them. :)

**Comment by nphmuller** [comment]
Nevermind, `yarn test` still fails:
```
 1 failing

  1) replaceTokens should succeed with default inputs:
     Error: done() invoked with non-Error: (node:4504) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4504) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4504) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4504) Warning: Use Cipheriv for counter mode of aes-256-ctr

      at Context.it (tests\_testsuite.ts:28:12)
```

**Comment by colindembovsky** [comment]
Hi @nphmuller - I am going to update the build/test docs. Also, I had the same issue with the `Cipheriv` warning, which unfortunately is a dependency issue (so there is some deep dependency that is using an old version of Cipheriv). The only way I could get around it is to ignore warnings (see the `NODE_NO_WARNINGS=1` [here](https://github.com/colindembovsky/cols-agent-tasks/blob/master/package.json#L15)).

**Comment by nphmuller** [comment]
Thanks! Much clearer now!
