### ISSUE TITLE
Apply json transformation with ReplaceToken

### ISSUE THREAD

**Issue by advapiIT** [colindembovsky/cols-agent-tasks#98]
I've successfully managed my token replace inside the web.config, now in the same application I've a appsettings.json with only one entry that's used from a module that's cross from  MVC / .NET Core
The structure is the following 

<pre>
{
  "ConnectionStrings": {
    "default": "server=xxx;database=xxx;user id=sys.xxx;password=123456;Application Name=ABC;"
  }
}
</pre>

How can I tell the token replacer to subtitute it?

I've tought of

<pre>
{
  "ConnectionStrings": {
    "default": "__default__"
  }
}
</pre>
And to put inside the parameters.xmls
parameter name="default" description="doesn't matter" defaultvalue="__default__" tags=""
    parameterentry kind="jsonFile" scope="\\appsettings.json" match="/configuration/default/add[@key='default']/@value"/
 lt&;/parameter

But I'm not sure of kind and if this's the right approach

Consider I've in the drop folder just the compressed file as you've specified inside the guide

Thanks and please excuse me if I bothered you

**Comment by colindembovsky** [comment]
Yes, you can do exactly that (with the parameters.xml file). The tricky part is getting the XPath to work. If you're using the latest Azure DevOps (VSTS) "IIS Deploy Task" or "Azure Web App Deploy Task" then you actually can do json and xml substitutions inline without needing the tokens at all. See [this post](https://colinsalmcorner.com/post/easy-config-management-when-deploying-azure-web-apps-from-vsts) for how this works.
